version: '3.8'

services:
  prometheus-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biconomy-prometheus-scraper
    restart: always
    stop_grace_period: 60s
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - BICONOMY_NODE_URL=${BICONOMY_NODE_URL:-http://localhost:3000}
      - SCRAPE_INTERVAL=${SCRAPE_INTERVAL:-30000}
      - ENABLE_NATIVE_BALANCE=${ENABLE_NATIVE_BALANCE:-true}
      - ENABLE_QUEUE_METRICS=${ENABLE_QUEUE_METRICS:-true}
      - ENABLE_HEALTH_CHECK=${ENABLE_HEALTH_CHECK:-true}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    profiles:
      - scraper
      - full

  prometheus:
    image: prom/prometheus:latest
    container_name: biconomy-prometheus
    restart: always
    stop_grace_period: 60s
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - prometheus-scraper
    profiles:
      - full

volumes:
  redis-data: 